sudo: required
services:
- docker
language: node_js
node_js: node
script:
- make lint
- make critique
before_deploy:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- make docker
deploy:
- provider: script
  script: make google-drive
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key:
    secure: ovR4ATmR+Xnapmpfz1epxn+qSLQZ2xjljkGTFHJpVP5Yr8WdqE/hnUsAvyG6QL44foZZfxvAL7f6eF4f4wm25vbFs2T0VtUPi0AcbDfYnSzhFZb/Xd26jMHzKByHbGgoqLVpW46FW8zROx57RgY+R51OlbifHeEvxbkkst9qAtlHyAQMyS21N0u8C1wSqowZBOzCHw5Vsu//37BqvqQpjs5HtLNiGP1jjeOhkLK9c0vIkDHHLHxQWcFly/AcylYkL/Xc7e2F47fG7SihRI/Z8jmgOrIrleHxDT8tCmB2gSslBR6Jo4G5cmNsMD89GRQmMp33oZ1/Bhc02jUbqBGOlLN+GGxKcAI0Ut89M5YXiNlKY0Da1u8t2upo+D49wi9ni+sMjLFeZAURrzHrePy2QpDsZQW7uvcM558ifr6OKBu8idVDNbsHg1Igyc+9C6bPn5lqcRRZLStRgxNFR3LKX77IyG8dWzghbqXweAb5kP58dg6/KAan83yKfHjfbIVlRollgrRBlvBwVoxMsJKOUJCZwwO7SYEzdYW2S0VZ0O3Iaz2bMT5RIVPvSp3yGuxVpOsU7X74Pr5UQtirPYGHGyo5mA2K3y4pCTxTrGbTyBnHM37gZLeDuaw9XXflJCT4P5hriIYQ5lQGxPjXlvNXWC3/Kox0cKAGGQkLbk9CtgI=
  skip_cleanup: true
  file_glob: true
  file: build/*
  on:
    tags: true
env:
  global:
  - secure: WgN5G7fI2BFgvDu8B0lCjR8LT07lgiw0cU2QWYQHCkC8f1lwkoJMcgYZT0trSJG1djnrypeS5ZZwCzAGVcBCD1qhXukD3bU3LPfJhcEIphKL/Bb4LGkTvaQveegxV72Ui+JfjIYSQiYhc12kzVTXM8y8OPLQHHY4NhHOBxi6VAX/5C+eTIt+702hTcmLZwBB2jWyLYrwjiv/4V/aRiEDfNfnW16vXkZpDFS3Y6C5LP/himohi2BM353ch8Ix9UcMWTJBk7CZ6XBSMdv1Ntm6q+TvwJWwjhbfRC18PE3EQAAO+kJfCqdhjcLqHRuUHes/uabYmHqSLCnCBXKHlgaSIhHrsrmLlHilED9d56pUdMogo32degTyzkJd4MLRpNwKz5zVvzpz7jS/sgqs9G+2kWBNJPGpQfBukv9j3IE5i7hTvgVNyOoDzmY+onhw8f++eikoqwp1tg+Ol9Rq3Q3aiZVv8wV29av/9NauUz1x4/vM28thP3ySaxdt8txdYzOeQ1aHfwTbQUn/O6DrT7dgRsmRy7XKSFU4GuuGF9u+0Qe8P6rgiRAS2gCJ6JUfItR5d5tuwUIJ5I+qz7Zv7YYrp1Xxp8cWIwv16BPRsGda8BQb8P1j7xfhI0Aqsy2+Pa7lKXT4Fvw8xPGY3s/AAkOrc/cf2Y96MEVLhv5K4GbJaA4=
  - secure: fnU49gstIwZ5kfSDsph2lJ3lexmR7DCiwtUanGDKm3ne54fKoH7IawygwvMWZsPdDZ6V5RGn1aZLNGsdid9pDIUJRVZHZ6HNHY+N28AD32Pjnxnaqki8/19N3rM33/P7Esjd7D7lQZOZt3iIo9tfV5Py/K9BXZT2VQIuZ9s5dKMV6Rigbis90S9o8jP3eGnxVSsz2tQEx5ob2HJtpe5KknL8iO38buXb9UcRlM+OaVFQen/MWi+ECvsjgtqlcas6wTjPk6TlRMp9x4LRTGp27lj6BrX1AGlL1q2u8eQAl03Fx9PaS6wo8QNs+GvV+/MZbcHcjZnz+qiQ1ZwNx1r2H2bUyunnSvfHPRJJAD/jyvikGccU5GzO27ftc8jDNKJa1ouk9GZXC2+7EHZ7hPOcnq3Zbsy34K/7YxsILvxL9JQ38o8OFfPAVj9dCpV+3Odm2cP5JnTL34aywBjGVnwWrTom28yM3CAyk6VfiE4V1GUA05veDV1DL5le8y6eQJLez/B9AmeobRn7WsApUEqODLIXo/1Rbd7Xg/rgOJpQFxkFWcmxWZSPG6mAeo86UQhbtKYG7hOUvug9g8Fw1ihc8bsjBXjr+ECz1YMLC80BFW8aTZAK/KWwRHBrXKY/1w8UWjY0s5iJpF8J1SKLg/UP2sCIoWK/W6LSpCXVAH25PBo=
  - secure: QMawEKgOAmxbAw+SKglQ19i2vjuE2xGeVK50bXUgtsm5A86Kfpx8G+1pV8Af2nY1fEtxnFbksNPRlwEGHvBEllo0C/nf/lOiyNDDYaD4EDBPKB55cjc3EQ40NOkLdPO7O5c6OhduSM3YS9emtQxvn/Vv3hS7rFh6Uo2a8mEWyvg8v+MxDD51cyl0oFXyB/UDAqOiRCwQQxzKOENgxMZHh+hgWn2WStjfZ+/gc0LWe/LrPjnzbWiCpwgVKWv81cEuqbr5t0NWGyt0XC6KgaIlbgKR9dihDSx7vXen/4qXnXUx1Qnm6hpK8REtJPWVOQ2EJ6PDIfKTwDbuQ7QVBoRcY/+er3QElBpLg0hGDc8ZlqzE4GMVdFoEDctLlUxZ/mY+dALxyN6pLYElF6Wg0wKgTnFeCGb1XZ9zpwCsQd1rJ2qouXV1E4uNWjlCE0Q3ceQP2Jb2ntu9XDLHaNrfVkXECBSAgdhM+lHs0woZca0QlAvzGZXf7xdZwBXUoesHL9uKA7eriEDDNW13MPk86bbMSQRXTitiHLE5WF/yubsaAcj8ZdRZxo7gUzJbq811mB0UyxRe9JESKZoQ9rU5k6Rk/cqmBiSe2cRstmCNl4PJEIhIY61olOb3z/7RoHxB1qVS4oE2+DdbUMSGijDHAEsck7j7KiEjvgLmWGCpFi8pCBg=
